name: Calculator
options:
  bundleIdPrefix: com.swiftgen
  deploymentTarget:
    iOS: 16.0
targets:
  Calculator:
    type: application
    platform: iOS
    sources: 
      - Sources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.swiftgen.calculator
      PRODUCT_NAME: Calculator
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_VERSION: 5.9
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      GENERATE_INFOPLIST_FILE: YES